### ISSUE TITLE
FromViewController有导航栏要返回时会crash

### ISSUE THREAD

**Issue by miss-yadi** [TuYuWang/TunViewControllerTransition#1]
FromViewController有导航栏要返回时会crash。

**Comment by miss-yadi** [comment]
我从另一个界面没有动画跳转过来，返回的时候也会有问题

**Comment by TuYuWang** [comment]
请贴一下你调用的代码部分

**Comment by miss-yadi** [comment]
FromViewController:
`- (void)viewDidAppear:(BOOL)animated
{
    [super viewDidAppear:animated];
    self.navigationController.delegate = self;
}`
`ToViewController *toController = [ToViewController spawn];

    TopicListCell *cell = [tableView cellForRowAtIndexPath:indexPath];
    [self animateTransitionFromView:cell.coverPhoto toView:@"header"];
    
    [self.navigationController pushViewController:toController animated:YES];`

ToViewController:
`     [self animateInverseTransition];
`

**Comment by miss-yadi** [comment]
跟README里是一样的 可以跳转成功也有动画，但是我的FromViewController返回时会crash。

**Comment by TuYuWang** [comment]
哪个类型的动画，还有crash信息

**Comment by miss-yadi** [comment]
![default](https://user-images.githubusercontent.com/10703305/34411024-113d14ae-ec0f-11e7-8ffa-8a185ebe83e6.png)
这是我FromViewController返回时crash在这里。动画类型为TunVCTransitionType_Transition。

**Comment by TuYuWang** [comment]
~~~
// toViewKeyPath 转场后的目标视图的keyPath（为toVC的属性），在demo中是imageView
- (void)animateTransitionFromView:(UIView *)view toView:(NSString *)toViewKeyPath;
~~~

**Comment by miss-yadi** [comment]
我在FromViewController中已经设置了。我的问题出在FromViewController要返回上级页面时会crash

**Comment by TuYuWang** [comment]
crash的原因是因为你的toViewController中找不到“header”这个属性。

**Comment by miss-yadi** [comment]
FromViewController跳转到ToViewController没有问题。ToViewController返回上级FromViewController也没有问题。问题是FromViewController再次返回上级页面时会crash。我觉得是navigationController的代理问题，但是不知道怎么修改

**Comment by TuYuWang** [comment]
问题已解决，谢谢反馈
